global:
  scrape_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:9090']

  # название приложение в docker-compose файле
  - job_name: 'booking'
    scrape_interval: 5s
    static_configs:
      # название приложение в docker-compose файле
      - targets: ['booking:8000']